version: '3.3'

services:
  etl_app:
    build: ./etl_app
    container_name: etl_container
    volumes:
      - mysql_volume:/usr/data/mongodb_data
    env_file:
      - ./.env.dev
    command: python etl.py 
    depends_on:
      - db
  db:
    image: mongo:5.0.4
    container_name: mongodb_etl_container
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'sparkifydb'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'  
    volumes:
       - mongodb_volume:/usr/data/mongodb_data 
       
volumes:
    mongodb_volume:
